name: CI

on: [push, pull_request]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_ossrhSigningKey: "${{ secrets.ossrhSigningKey }}"
      ORG_GRADLE_PROJECT_ossrhSigningPassword: "${{ secrets.ossrhSigningPassword }}"
      ORG_GRADLE_PROJECT_ossrhPassword: "${{ secrets.ossrhPassword }}"
      ORG_GRADLE_PROJECT_ossrhUser: "${{ secrets.ossrhUser }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Setup Java JDK
        uses: actions/setup-java@v2.4.0
        with:
          java-version: 11
          distribution: temurin

      - name: Build
        run: ./gradlew build --info --console=plain

      - name: Release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./gradlew releaseVersion --no-commit --info --console=plain

      - name: Push Release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: git push --tags

      - name: Publish
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./gradlew publishToOSSRH closeAndReleaseOSSRHStagingRepository --info --console=plain

